### ISSUE TITLE
files icons for Subime 3

### ISSUE THREAD

**Issue by maqboolkhan** [samuelrafo/piatto#20]
To be honest this theme is awesome and it looks more awesome with windows 8 and 10 ! no complains but there is a quick suggestion that if you can add you must add **`files icons`** so it will look more awesome :)

**Comment by samuelrafo** [comment]
added now, thanks for feedback

**Comment by maqboolkhan** [comment]
@samuelrafo thank u so much :+1: one more suggestion what about removing arrow next to the folder icon? then we have more space?

**Comment by samuelrafo** [comment]
I will add an option to disable the arrows, thanks for the suggestion
