### ISSUE TITLE
Folder icons don't work

### ISSUE THREAD

**Issue by AlexVPopov** [samuelrafo/piatto#23]
Hello,

Since the 2.0 update the folder icons no longer work. I have the right settings in my User - Settings file:

```
"piatto_folder_icons": true,
```

but I don't see the icons. I don't know if this is relevant, but I see the following erros in the log

``` log
found 1 files for base name Piatto Light.sublime-theme
Errors parsing theme:
Unknown attribute value
Unknown attribute value
Animated properties must have both target and speed specified
theme loaded
```

**Comment by samuelrafo** [comment]
What is the ST version are you using? In the latest builds of ST3 it's not necessary to use this setting because the folder icons are shown by default

**Comment by AlexVPopov** [comment]
Sorry for missing to point that. I am using the latest build of ST2.
