### ISSUE TITLE
"go to" panel not properly styled for dark theme

### ISSUE THREAD

**Issue by vaiRk** [samuelrafo/piatto#24]
Since last update the "Go to" panel is not properly styled for the dark version, making the text almost unreadable :(

![screen shot 2016-03-02 at 10 29 19](https://cloud.githubusercontent.com/assets/1123924/13457819/f8627632-e061-11e5-827e-185e89e81806.png)

**Comment by thorstenkampe** [comment]
Same here with `Piatto Light 3`...

Before: 
![image](https://cloud.githubusercontent.com/assets/475462/13492339/b726145e-e137-11e5-9d03-0abad8328fe5.png)

After:
![image](https://cloud.githubusercontent.com/assets/475462/13492345/c297a23a-e137-11e5-8745-86eb2e5c51cc.png)

**Comment by aivot-on** [comment]
Had the same issue with light theme.
It appears the theme name changed from "Piatto Light 3.sublime-theme" to "Piatto Light.sublime-theme".
I assume the same goes with the dark theme.

**Comment by samuelrafo** [comment]
"Piatto Light 3.sublime-theme" was changed to "Piatto Light.sublime-theme" by default, this also applies to the Dark version. I'm solving the problem on the panel "go to" for some unknown reason it does not use the background texture used in other panels (such as "command pallete", etc.). It will be fixed soon. Thanks for the feedback.

**Comment by vaiRk** [comment]
Fixed. Amazing. @samuelrafo :clap: :clap: :clap: :clap: :clap: :clap:  thanks!
